package kr.gooroom.gpms.grm.serveragent.service;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface ClientJobService {

	int insertLogUpdate(LogUpdateVO log) throws Exception;
	int insertOrUpdateClientExt(ClientInfoVO clientInfo) throws Exception;
	PackageServerVO selectUpdateServerFiles(String clientId) throws Exception;
	String selectEtcHostsContents(String clientId) throws Exception;
	String selectCert(String clientId) throws Exception;
	int insertOrUpdatePackage(List<PackageVO> packageVoList) throws Exception;
	int insertOrUpdatePackageState(String clientId) throws Exception;
	int deletePackage(PackageVO packageVo) throws Exception;
	int deletePackageMstr() throws Exception;
	int insertPackageMstr(List<PackageVO> packageVoList) throws Exception;
	int insertLogSecurity(List<LogSecurityVO> logSecurityVoList) throws Exception;
	int insertLogSecurity2(List<LogSecurity2VO> logSecurity2VoList) throws Exception;
	int insertOrUpdateClientSecurityState(ClientSecurityStateVO clientSecurityStateVo) throws Exception;
	int insertOrUpdateClientSecurityStateClear(ClientSecurityStateVO clientSecurityStateVo) throws Exception;
	int insertClientExtHist(String clientId) throws Exception;
	int insertClientSecurityStateHist(String clientId) throws Exception;
	String selectOneServerjobDispatchTime(String siteName) throws Exception;
	String selectOneServerjobMaxMediaCnt(String siteName) throws Exception;
	int insertLogGeneral(List<LogGeneralVO> vos) throws Exception;
	String selectClientCertificate(String clientId) throws Exception;
	String selectHypervisorOperation(String clientId) throws Exception;
	String selectUpdateOperation(ClientLoginVO clVo) throws Exception;
	List<String> selectPackageList(String clientId) throws Exception;
	int insertProfilingPackage(List<ProfileVO> profileVoList) throws Exception;
	List<String> selectProfilingPackageList(String profileNo) throws Exception;
	String selectServerVersion(String siteName) throws Exception;
	String selectPasswordCycle(ClientLoginVO clVo) throws Exception;
	String selectScreenTime(ClientLoginVO clVo) throws Exception;
	List<String> selectAppBlackList(ClientLoginVO clVo) throws Exception;
	String selectHomefolderOperation(String clientId) throws Exception;
	List<String> selectIpWhiteList(String clientId) throws Exception;
	ThemeVO selectThemeInfo(HashMap<String, Object> options) throws Exception;
	SchedInfoVO selectSchedInfo(String clientId) throws Exception;
	int insertSchedInfo(SchedInfoVO schedInfo) throws Exception;
	int updateSchedInfo(List<SchedInfoVO> schedInfo) throws Exception;
	List<NotiVO> selectNoti(ClientLoginVO vo) throws Exception;
	String selectDefaultNotiDomain() throws Exception;
	List<NotiVO> selectInstanceNoti(Map<String, Object> params) throws Exception;
	int insertLogBrowser(List<LogBrowserVO> vos) throws Exception;
	int deleteClientPackage(String clientId) throws Exception;
	List<String> selectAllClients() throws Exception;
	List<String> selectControlcenterItems(ClientLoginVO clVo) throws Exception;
	int updatePollingTime(PollingTimeVO vo) throws Exception;
	String selectRootUse(String clientId) throws Exception;
	String selectSudoUse(String clientId) throws Exception;
	String selectPolkitAdmin(String clientId) throws Exception;
	String selectCleanModeUse(String clientId) throws Exception;
	int insertUserReqMstr (UserReqVO urVo) throws Exception;
	int insertUserReqProp (UserReqVO urVo) throws Exception;
	String selectRegisterReqMod(String siteName) throws Exception;
	String selectDeleteReqMod(String siteName) throws Exception;
	String selectUserReqSeq(UserReqVO urVo) throws Exception;
	String selectUserReqPropSeq(UserReqVO urVo) throws Exception;
	int deleteUserReqMstr(UserReqVO urVo) throws Exception;
	int deleteUserReqProp(UserReqVO urVo) throws Exception;
	List<UserReqVO> selectUserUsbMediaList(UserReqVO urmVo) throws Exception;
	int updateUserReqProp(UserReqVO urVo) throws Exception;
	String selectExistMediaRegisterReq(UserReqVO urVo) throws Exception;
	String selectExistMediaUnRegisterReq(UserReqVO urVo) throws Exception;
	String selectExistMedia(UserReqVO urVo) throws Exception;
	String selectRegisteredReqSeq(UserReqVO urVo) throws Exception;
	int updateReqProp(UserReqVO urVo) throws Exception;
	int updateReqMstr(UserReqVO urVo) throws Exception;
	UserReqVO selectUserReq(String reqSeq) throws Exception;
	int insertUserReqHist(UserReqVO urVo) throws Exception;
	String selectReqSeqNo(UserReqVO urVo) throws Exception;
	String selectOnlineClientIdInClientId(String reqSeq) throws Exception;
	long createJobMaster(JobVO jobVO) throws Exception;
	long createJobTarget(JobVO jobVO) throws Exception;

}
